language: typescript
imports:
  - backendtlspolicy:=crds/crd-gateway-api-backendtlspolicies.yaml
  - gatewayclass:=crds/crd-gateway-api-gatewayclasses.yaml
  - gateway:=crds/crd-gateway-api-gateways.yaml
  - grpcroute:=crds/crd-gateway-api-grpcroutes.yaml
  - httproute:=crds/crd-gateway-api-httproutes.yaml
  - listenerset:=crds/crd-gateway-api-listenersets.yaml
  - referencegrant:=crds/crd-gateway-api-referencegrants.yaml
  - tcproute:=crds/crd-gateway-api-tcproutes.yaml
  - tlsroute:=crds/crd-gateway-api-tlsroutes.yaml
  - udproute:=crds/crd-gateway-api-udproutes.yaml
  - vapsafeupgrade:=crds/crd-gateway-api-vap-safeupgrades.yaml
  - inferencepool:=crds/crd-inference-ext-inferencepools.yaml
  - inferencepoolimport:=crds/crd-inference-ext-inferencepoolimports.yaml
  - istio:=crds/crd-istio-all.yaml
  - dnsendpoint:=crds/crd-external-dns-dnsendpoints.yaml
  - backendconfigpolicy:=crds/crd-kgateway-backendconfigpolicies.yaml
  - backend:=crds/crd-kgateway-backends.yaml
  - directresponse:=crds/crd-kgateway-directresponses.yaml
  - gatewayextension:=crds/crd-kgateway-gatewayextensions.yaml
  - gatewayparameter:=crds/crd-kgateway-gatewayparameters.yaml
  - httplistenerpolicy:=crds/crd-kgateway-httplistenerpolicies.yaml
  - listenerpolicy:=crds/crd-kgateway-listenerpolicies.yaml
  - trafficpolicy:=crds/crd-kgateway-trafficpolicies.yaml
  - ciliumbgpadvertisement:=crds/crd-cilium-bgpadvertisements.yaml
  - ciliumbgpclusterconfig:=crds/crd-cilium-bgpclusterconfigs.yaml
  - ciliumbgpnodeconfigoverride:=crds/crd-cilium-bgpnodeconfigoverrides.yaml
  - ciliumbgpnodeconfig:=crds/crd-cilium-bgpnodeconfigs.yaml
  - ciliumbgppeerconfig:=crds/crd-cilium-bgppeerconfigs.yaml
  - ciliumcidrgroup:=crds/crd-cilium-cidrgroups.yaml
  - ciliumclusterwideenvoyconfig:=crds/crd-cilium-clusterwideenvoyconfigs.yaml
  - ciliumclusterwidenetworkpolicy:=crds/crd-cilium-clusterwidenetworkpolicies.yaml
  - ciliumegressgatewaypolicy:=crds/crd-cilium-egressgatewaypolicies.yaml
  - ciliumendpoint:=crds/crd-cilium-endpoints.yaml
  - ciliumenvoyconfig:=crds/crd-cilium-envoyconfigs.yaml
  - ciliumidentity:=crds/crd-cilium-identities.yaml
  - ciliumloadbalancerippool:=crds/crd-cilium-loadbalancerippools.yaml
  - ciliumlocalredirectpolicy:=crds/crd-cilium-localredirectpolicies.yaml
  - ciliumnetworkpolicy:=crds/crd-cilium-networkpolicies.yaml
  - ciliumnodeconfig:=crds/crd-cilium-nodeconfigs.yaml
  - ciliumnode:=crds/crd-cilium-nodes.yaml
  - clusterproxy:=crds/crd-netbird-clusterproxies.yaml
  - nbgroup:=crds/crd-netbird-nbgroups.yaml
  - nbpolicy:=crds/crd-netbird-nbpolicies.yaml
  - nbresource:=crds/crd-netbird-nbresources.yaml
  - nbroutingpeer:=crds/crd-netbird-nbroutingpeers.yaml
  - nbsetupkey:=crds/crd-netbird-nbsetupkeys.yaml
  - networkegress:=crds/crd-netbird-networkegresses.yaml
  - networkresource:=crds/crd-netbird-networkresources.yaml
  - networkrouter:=crds/crd-netbird-networkrouters.yaml
  - setupkey:=crds/crd-netbird-setupkeys.yaml
  - sidecarprofile:=crds/crd-netbird-sidecarprofiles.yaml
