/*
 * Copyright (c) 2026 Sumicare Contributors
 *
 * Licensed under the terms of MIT License
 */

import { KnownLatestKedaVersion } from "Compute/Keda/Version";
import {
	defineConfig,
	type InferConfig,
	OpenBaoSpcSchema,
	ProbeSchema,
	ResourceTierSchema,
} from "@sumicare/chart-commons";
import { z } from "zod";

const LoggingSchema = z.object({
	level: z
		.string()
		.describe("Logging level (debug, info, error, or integer > 0)")
		.default("info"),
	format: z
		.string()
		.describe("Logging format (json or console)")
		.default("console"),
	timeEncoding: z
		.string()
		.describe(
			"Logging time encoding (epoch, millis, nano, iso8601, rfc3339, rfc3339nano)",
		)
		.default("rfc3339"),
});

const ComponentConfigSchema = z.object({
	replicas: z.number().min(1).describe("Number of pod replicas").default(1),
	revisionHistoryLimit: z
		.number()
		.min(0)
		.describe("Number of old ReplicaSets to retain")
		.default(10),
	resourceTier: ResourceTierSchema.describe(
		"Resource tier for this component",
	).default("S"),
	livenessProbe: ProbeSchema.describe("Liveness probe configuration").prefault(
		{},
	),
	readinessProbe: ProbeSchema.describe(
		"Readiness probe configuration",
	).prefault({}),
});

const OperatorConfigSchema = ComponentConfigSchema.extend({
	name: z
		.string()
		.describe("Name of the KEDA operator")
		.default("keda-operator"),
	disableCompression: z
		.boolean()
		.describe("Disable response compression for k8s restAPI in client-go")
		.default(true),
});

const MetricsServerConfigSchema = ComponentConfigSchema.extend({
	enabled: z
		.boolean()
		.describe("Enable KEDA metrics server and external metrics API resources")
		.default(true),
	disableCompression: z
		.boolean()
		.describe("Disable response compression for k8s restAPI in client-go")
		.default(true),
});

const WebhooksConfigSchema = ComponentConfigSchema.extend({
	enabled: z
		.boolean()
		.describe(
			"Enable KEDA admission webhooks and webhook patching in the operator",
		)
		.default(true),
	name: z
		.string()
		.describe("Name of the KEDA admission webhooks")
		.default("keda-admission-webhooks"),
	port: z
		.number()
		.min(1)
		.max(65535)
		.describe("Port for KEDA admission webhooks")
		.default(9443),
	healthProbePort: z
		.number()
		.min(1)
		.max(65535)
		.describe("Port for KEDA admission webhooks health probe")
		.default(8081),
	failurePolicy: z
		.enum(["Ignore", "Fail"])
		.describe("Failure policy for admission webhooks")
		.default("Ignore"),
	timeoutSeconds: z
		.number()
		.min(1)
		.describe("Timeout in seconds for KEDA admission webhooks")
		.default(10),
});

const CertificatesSchema = z.object({
	autoGenerated: z
		.boolean()
		.describe(
			"Enables self-generation of KEDA TLS certificates inside the operator",
		)
		.default(true),
	secretName: z
		.string()
		.describe("Secret name for KEDA TLS certificates")
		.default("kedaorg-certs"),
	mountPath: z
		.string()
		.describe("Path where KEDA TLS certificates are mounted")
		.default("/certs"),
});

const ServiceSchema = z.object({
	portHttps: z
		.number()
		.min(1)
		.max(65535)
		.describe("HTTPS port for KEDA Metric Server service")
		.default(443),
	portHttpsTarget: z
		.number()
		.min(1)
		.max(65535)
		.describe("HTTPS target port for KEDA Metric Server container")
		.default(6443),
});

const kedaConfig = defineConfig({
	chartName: "KedaChart",
	base: ["revisionHistoryLimit"],
	shared: ["disableMetrics", "environments"],
	fields: {
		name: z
			.string()
			.describe("Base name for KEDA resources")
			.default("keda-operator"),
		namespace: z
			.string()
			.describe("Kubernetes namespace where KEDA will be deployed")
			.default("keda"),
		version: z
			.string()
			.describe("KEDA container image version")
			.default(KnownLatestKedaVersion),
		operatorImage: z
			.string()
			.describe(
				"KEDA operator image. Defaults to ghcr.io/kedacore/keda:<version>",
			)
			.optional(),
		metricsServerImage: z
			.string()
			.describe(
				"KEDA metrics server image. Defaults to ghcr.io/kedacore/keda-metrics-apiserver:<version>",
			)
			.optional(),
		webhooksImage: z
			.string()
			.describe(
				"KEDA admission webhooks image. Defaults to ghcr.io/kedacore/keda-admission-webhooks:<version>",
			)
			.optional(),
		imagePullPolicy: z
			.enum(["Always", "IfNotPresent", "Never"])
			.describe("Image pull policy for all KEDA components")
			.default("IfNotPresent"),
		watchNamespace: z
			.string()
			.describe("Kubernetes namespaces to watch. Empty watches all namespaces")
			.default(""),
		clusterName: z
			.string()
			.describe("Kubernetes cluster name, used for emitting CloudEvents")
			.default("kubernetes-default"),
		clusterDomain: z
			.string()
			.describe("Kubernetes cluster domain")
			.default("cluster.local"),
		runAsUser: z
			.number()
			.describe("UID to run KEDA containers as")
			.default(1000),
		runAsGroup: z
			.number()
			.describe("GID to run KEDA containers as")
			.default(1000),
		fsGroup: z.number().describe("FS group for mounted volumes").default(1000),
		operator: OperatorConfigSchema.describe(
			"KEDA operator configuration",
		).prefault({}),
		metricsServer: MetricsServerConfigSchema.describe(
			"KEDA metrics server configuration",
		).prefault({}),
		webhooks: WebhooksConfigSchema.describe(
			"KEDA admission webhooks configuration",
		).prefault({}),
		certificates: CertificatesSchema.describe(
			"KEDA TLS certificate configuration",
		).prefault({}),
		service: ServiceSchema.describe(
			"KEDA metric server service configuration",
		).prefault({}),
		logging: z
			.object({
				operator: LoggingSchema.describe("Logging for KEDA operator").prefault(
					{},
				),
				metricServer: z
					.object({
						zapLevel: z.string().describe("Zap logging level").default("info"),
						zapEncoder: z
							.string()
							.describe("Zap logging encoder")
							.default("console"),
						zapTimeEncoding: z
							.string()
							.describe("Zap logging time encoding")
							.default("rfc3339"),
					})
					.describe("Logging for KEDA metrics server")
					.prefault({}),
				webhooks: LoggingSchema.describe(
					"Logging for KEDA admission webhooks",
				).prefault({}),
			})
			.describe("Logging configuration for all KEDA components")
			.prefault({}),
		http: z
			.object({
				timeout: z
					.number()
					.describe("Default HTTP timeout in milliseconds")
					.default(3000),
				minTlsVersion: z
					.string()
					.describe("Minimum TLS version for HTTP clients")
					.default("TLS12"),
			})
			.describe("HTTP client configuration")
			.prefault({}),
		secretProviderClass: OpenBaoSpcSchema.prefault({}).describe(
			"OpenBao CSI SecretProviderClass configuration for HTTPS metrics certs",
		),
	},
	resolveConfig: (parsed) => {
		const version = parsed.version as string;
		const resolveImage = (
			img: string | undefined,
			defaultRepo: string,
		): string => {
			if (img) return img;
			return `${defaultRepo}:${version}`;
		};
		return {
			...parsed,
			operatorImage: resolveImage(
				parsed.operatorImage as string | undefined,
				"ghcr.io/kedacore/keda",
			),
			metricsServerImage: resolveImage(
				parsed.metricsServerImage as string | undefined,
				"ghcr.io/kedacore/keda-metrics-apiserver",
			),
			webhooksImage: resolveImage(
				parsed.webhooksImage as string | undefined,
				"ghcr.io/kedacore/keda-admission-webhooks",
			),
		};
	},
});

export const KedaConfigSchema = kedaConfig.schema;
export const KedaConfigError = kedaConfig.ConfigError;
export { kedaConfig };

export type Config = InferConfig<typeof kedaConfig>;
