/*
 * Copyright (c) 2026 Sumicare Contributors
 *
 * Licensed under the terms of MIT License
 */

import type { Config } from "Compute/Keda/Config";
import { defineDeployment, hardenedContainer } from "@sumicare/chart-commons";
import { JsonPatch } from "cdk8s";
import {
	ConnectionScheme,
	type IServiceAccount,
	Secret,
	Volume,
} from "cdk8s-plus-33";
import type { Construct } from "constructs";

type KedaDeploymentProps = Config & {
	operatorSa: IServiceAccount;
	metricsServerSa: IServiceAccount;
	webhooksSa: IServiceAccount;
};

function createCertVolume(
	scope: Construct,
	id: string,
	secretName: string,
): {
	volume: Volume;
	mount: { volume: Volume; path: string; readOnly: boolean };
} {
	const certSecret = Secret.fromSecretName(
		scope,
		`${id}-cert-secret`,
		secretName,
	);
	const volume = Volume.fromSecret(scope, `${id}-cert-volume`, certSecret, {
		name: "certificates",
	});
	return {
		volume,
		mount: { volume, path: "/certs", readOnly: true },
	};
}

const KedaDeployments = defineDeployment<KedaDeploymentProps>({
	deployments: (scope, props) => {
		const operatorCert = createCertVolume(
			scope,
			"operator",
			props.certificates.secretName,
		);
		const metricsCert = createCertVolume(
			scope,
			"metrics-server",
			props.certificates.secretName,
		);
		const webhooksCert = createCertVolume(
			scope,
			"webhooks",
			props.certificates.secretName,
		);

		const operatorArgs = [
			"--leader-elect",
			`--disable-compression=${props.operator.disableCompression}`,
			`--zap-log-level=${props.logging.operator.level}`,
			`--zap-encoder=${props.logging.operator.format}`,
			`--zap-time-encoding=${props.logging.operator.timeEncoding}`,
			`--enable-webhook-patching=${props.webhooks.enabled}`,
			`--cert-dir=${props.certificates.mountPath}`,
			`--enable-cert-rotation=${props.certificates.autoGenerated}`,
			`--cert-secret-name=${props.certificates.secretName}`,
			`--operator-service-name=${props.operator.name}`,
			`--metrics-server-service-name=${props.operator.name}-metrics-apiserver`,
			`--webhooks-service-name=${props.webhooks.name}`,
			`--k8s-cluster-name=${props.clusterName}`,
			`--k8s-cluster-domain=${props.clusterDomain}`,
			"--enable-prometheus-metrics=false",
		];

		const metricsArgs = [
			`--port=8080`,
			`--secure-port=${props.service.portHttpsTarget}`,
			"--logtostderr=true",
			"--stderrthreshold=ERROR",
			`--disable-compression=${props.metricsServer.disableCompression}`,
			`--metrics-service-address=${props.operator.name}.${props.namespace}.svc.${props.clusterDomain}:9666`,
			`--client-ca-file=${props.certificates.mountPath}/ca.crt`,
			`--tls-cert-file=${props.certificates.mountPath}/tls.crt`,
			`--tls-private-key-file=${props.certificates.mountPath}/tls.key`,
			`--cert-dir=${props.certificates.mountPath}`,
			"--v=0",
			`--zap-log-level=${props.logging.metricServer.zapLevel}`,
			`--zap-encoder=${props.logging.metricServer.zapEncoder}`,
			`--zap-time-encoding=${props.logging.metricServer.zapTimeEncoding}`,
		];

		const webhooksArgs = [
			`--zap-log-level=${props.logging.webhooks.level}`,
			`--zap-encoder=${props.logging.webhooks.format}`,
			`--zap-time-encoding=${props.logging.webhooks.timeEncoding}`,
			`--cert-dir=${props.certificates.mountPath}`,
			`--health-probe-bind-address=:${props.webhooks.healthProbePort}`,
			`--port=${props.webhooks.port}`,
			"--metrics-bind-address=:8080",
		];

		return [
			{
				id: "operator-deployment",
				name: props.operator.name,
				component: "operator",
				replicas: props.operator.replicas,
				revisionHistoryLimit:
					props.operator.revisionHistoryLimit ?? props.revisionHistoryLimit,
				serviceAccount: props.operatorSa,
				automountServiceAccountToken: true,
				podSecurityContext: {
					runAsUser: props.runAsUser,
					runAsGroup: props.runAsGroup,
					fsGroup: props.fsGroup,
				},
				applyPodSeccomp: false,
				containers: [
					{
						name: "keda-operator",
						image: props.operatorImage,
						imagePullPolicy: props.imagePullPolicy,
						command: ["/keda"],
						args: operatorArgs,
						ports: [{ number: 9666, name: "metricsservice" }],
						resources: props.operator.resourceTier,
						liveness: {
							path: "/healthz",
							port: 8081,
							...props.operator.livenessProbe,
						},
						readiness: {
							path: "/readyz",
							port: 8081,
							...props.operator.readinessProbe,
						},
						securityContext: hardenedContainer(),
						volumeMounts: [operatorCert.mount],
					},
				],
				volumes: [operatorCert.volume],
				extraPatches: [
					JsonPatch.add("/spec/template/spec/containers/0/env", [
						{ name: "WATCH_NAMESPACE", value: props.watchNamespace },
						{
							name: "POD_NAME",
							valueFrom: {
								fieldRef: { fieldPath: "metadata.name" },
							},
						},
						{
							name: "POD_NAMESPACE",
							valueFrom: {
								fieldRef: { fieldPath: "metadata.namespace" },
							},
						},
						{ name: "OPERATOR_NAME", value: props.operator.name },
						{
							name: "KEDA_HTTP_DEFAULT_TIMEOUT",
							value: String(props.http.timeout),
						},
						{
							name: "KEDA_HTTP_MIN_TLS_VERSION",
							value: props.http.minTlsVersion,
						},
					]),
				],
			},
			{
				id: "metrics-server-deployment",
				name: `${props.operator.name}-metrics-apiserver`,
				component: "metrics-server",
				replicas: props.metricsServer.replicas,
				revisionHistoryLimit:
					props.metricsServer.revisionHistoryLimit ??
					props.revisionHistoryLimit,
				serviceAccount: props.metricsServerSa,
				automountServiceAccountToken: true,
				podSecurityContext: {
					runAsUser: props.runAsUser,
					runAsGroup: props.runAsGroup,
					fsGroup: props.fsGroup,
				},
				applyPodSeccomp: false,
				when: (p) => p.metricsServer.enabled,
				containers: [
					{
						name: "keda-operator-metrics-apiserver",
						image: props.metricsServerImage,
						imagePullPolicy: props.imagePullPolicy,
						command: ["/keda-adapter"],
						args: metricsArgs,
						ports: [
							{ number: props.service.portHttpsTarget, name: "https" },
							{ number: 8080, name: "metrics" },
						],
						resources: props.metricsServer.resourceTier,
						liveness: {
							path: "/healthz",
							port: props.service.portHttpsTarget,
							scheme: ConnectionScheme.HTTPS,
							...props.metricsServer.livenessProbe,
						},
						readiness: {
							path: "/readyz",
							port: props.service.portHttpsTarget,
							scheme: ConnectionScheme.HTTPS,
							...props.metricsServer.readinessProbe,
						},
						securityContext: hardenedContainer(),
						volumeMounts: [metricsCert.mount],
					},
				],
				volumes: [metricsCert.volume],
				extraPatches: [
					JsonPatch.add("/spec/template/spec/containers/0/env", [
						{ name: "WATCH_NAMESPACE", value: props.watchNamespace },
						{
							name: "POD_NAMESPACE",
							valueFrom: {
								fieldRef: { fieldPath: "metadata.namespace" },
							},
						},
						{
							name: "KEDA_HTTP_DEFAULT_TIMEOUT",
							value: String(props.http.timeout),
						},
						{
							name: "KEDA_HTTP_MIN_TLS_VERSION",
							value: props.http.minTlsVersion,
						},
					]),
				],
			},
			{
				id: "webhooks-deployment",
				name: props.webhooks.name,
				component: "webhooks",
				replicas: props.webhooks.replicas,
				revisionHistoryLimit:
					props.webhooks.revisionHistoryLimit ?? props.revisionHistoryLimit,
				serviceAccount: props.webhooksSa,
				automountServiceAccountToken: true,
				podSecurityContext: {
					runAsUser: props.runAsUser,
					runAsGroup: props.runAsGroup,
					fsGroup: props.fsGroup,
				},
				applyPodSeccomp: false,
				when: (p) => p.webhooks.enabled,
				containers: [
					{
						name: "keda-admission-webhooks",
						image: props.webhooksImage,
						imagePullPolicy: props.imagePullPolicy,
						command: ["/keda-admission-webhooks"],
						args: webhooksArgs,
						ports: [{ number: props.webhooks.port, name: "http" }],
						resources: props.webhooks.resourceTier,
						liveness: {
							path: "/healthz",
							port: props.webhooks.healthProbePort,
							...props.webhooks.livenessProbe,
						},
						readiness: {
							path: "/readyz",
							port: props.webhooks.healthProbePort,
							...props.webhooks.readinessProbe,
						},
						securityContext: hardenedContainer(),
						volumeMounts: [webhooksCert.mount],
					},
				],
				volumes: [webhooksCert.volume],
				extraPatches: [
					JsonPatch.add("/spec/template/spec/containers/0/env", [
						{ name: "WATCH_NAMESPACE", value: props.watchNamespace },
						{
							name: "POD_NAME",
							valueFrom: {
								fieldRef: { fieldPath: "metadata.name" },
							},
						},
						{
							name: "POD_NAMESPACE",
							valueFrom: {
								fieldRef: { fieldPath: "metadata.namespace" },
							},
						},
					]),
				],
			},
		];
	},
});

export type KedaDeploymentConstruct = InstanceType<typeof KedaDeployments>;

export function createKedaDeployment(
	scope: Construct,
	config: Config,
	operatorSa: IServiceAccount,
	metricsServerSa: IServiceAccount,
	webhooksSa: IServiceAccount,
): KedaDeploymentConstruct {
	return new KedaDeployments(scope, "deployments", {
		...config,
		operatorSa,
		metricsServerSa,
		webhooksSa,
	});
}
